# Generated by Django 3.1.6 on 2021-02-24 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('email', models.EmailField(max_length=64)),
                ('phone', models.CharField(max_length=10)),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('email', models.EmailField(max_length=64)),
                ('address', models.CharField(max_length=300)),
                ('city', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=20)),
                ('zip_code', models.CharField(max_length=6)),
                ('phone', models.CharField(max_length=10)),
                ('cartcontent', models.TextField()),
                ('amount', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=300)),
                ('price', models.IntegerField()),
                ('category', models.CharField(choices=[('Marble Vases', 'Marble Vases'), ('Marble Lamps', 'Marble Lamps'), ('Marble Decorative', 'Marble Decorative'), ('Marble Artifacts', 'Marble Artifacts'), ('Marble Paintings', 'Marble Paintings'), ('Decorative Marble Pen Stands', 'Decorative Marble Pen Stands')], max_length=50)),
                ('size', models.CharField(default='15"x15"x25"', max_length=35)),
                ('material', models.CharField(default='Makrana Marble', max_length=20)),
                ('color', models.CharField(default='White', max_length=15)),
                ('publish_date', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(upload_to='shop/products/images')),
                ('instock', models.BooleanField(default=True)),
                ('featured', models.BooleanField(default=False)),
                ('minbuy', models.IntegerField(default=1)),
            ],
        ),
    ]
