# Generated by Django 3.1.6 on 2021-02-28 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imageId', models.IntegerField()),
                ('image', models.ImageField(upload_to='shop/products/images')),
            ],
        ),
    ]
